add_subdirectory(code_00_raytracer)
add_subdirectory(code_01_setup_glfw)
add_subdirectory(code_02_my_first_triangle)
add_subdirectory(code_03_wrapping_shaders_buffers)
add_subdirectory(code_04_robotic_arm_transformations)
add_subdirectory(code_05_assonometry)
add_subdirectory(code_06_arm_rotations)
add_subdirectory(code_07_trackball)
add_subdirectory(code_08_raster)
add_subdirectory(code_09_lighting_shading)
add_subdirectory(code_10_gltf_loader)
add_subdirectory(code_11_metaballs)
add_subdirectory(code_12_texture_mapping)
add_subdirectory(code_13_shadows)
add_subdirectory(code_14_ambient_obscurance)
add_subdirectory(code_15_fsq_raytracer)
add_subdirectory(code_16_cs_raytracer)
add_subdirectory(code_17_hybrid_renderer)
add_subdirectory(code_carousel)
add_subdirectory(code_carousel_raytracing)



